package com.redhat.datamodeler;

/**
 * This class was automatically generated by the data modeler tool.
 */
@org.jbpm.datamodeler.annotations.Description("This clase is an Invoice")
@org.jbpm.datamodeler.annotations.Label("InvoiceLabel")
public class Invoice {
    
    @org.jbpm.datamodeler.annotations.Description(value = "This field is used to test a java.util.List as the bag collection.")
    private java.util.List<com.redhat.datamodeler.InvoiceLine> lines;

    @org.jbpm.datamodeler.annotations.Label(value = "LinesArrayLabel")
    @org.jbpm.datamodeler.annotations.Description(value = "This field is used to test a java.util.ArrayList as the bag collection.")
    private java.util.ArrayList<com.redhat.datamodeler.InvoiceLine> linesarray;

    @org.jbpm.datamodeler.annotations.Description(value = "This field is used to test a java.util.HashSet as the bag collection.")
    private java.util.HashSet<com.redhat.datamodeler.InvoiceLine> linesset;

    @org.jbpm.datamodeler.annotations.Description("The invoice number is a unique generated by system number")
    @org.jbpm.datamodeler.annotations.Label(value = "InvoiceNumberLabel")
    private java.lang.Short invoicenumber;

    public Invoice() {

    }
    
    public java.util.List<com.redhat.datamodeler.InvoiceLine> getLines() {
        return this.lines;
    }

    public void setLines(  java.util.List<com.redhat.datamodeler.InvoiceLine> lines ) {
        this.lines = lines;
    }

    public java.util.ArrayList<com.redhat.datamodeler.InvoiceLine> getLinesarray() {
        return this.linesarray;
    }

    public java.util.HashSet<com.redhat.datamodeler.InvoiceLine> getLinesset() {
        return this.linesset;
    }
    
    public java.lang.Short getInvoicenumber() {
        return this.invoicenumber;
    }

    public void setInvoicenumber(  java.lang.Short invoicenumber ) {
        this.invoicenumber = invoicenumber;
    }
    
    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;

        //TODO complete this implementation
        return false;
    }
    
    @Override
    public int hashCode() {
        //TODO complete this implementation
        return -670115059;
    }

}

