package com.redhat.datamodeler;

/**
 * This class was automatically generated by the data modeler tool.
 */
public class InvoiceLine {
    
    @org.jbpm.datamodeler.annotations.Description(value = "This field holds the article for this line")
    @org.jbpm.datamodeler.annotations.Label("ArticleLabel")
    private java.lang.String article;

    public InvoiceLine() {

    }
    
    public java.lang.String getArticle() {
        return this.article;
    }

    public void setArticle(  java.lang.String article ) {
        this.article = article;
    }
    
    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;

        //TODO complete this implementation
        return false;
    }
    
    @Override
    public int hashCode() {
        //TODO complete this implementation
        return 805613729;
    }

}

